module KitchenNaming
{
  interface Kitchen
  {
    string turnOnOff(in string json);
    string changeHeat(in string json);
    string openCloseDoor(in string json);
    string setTimer(in string json);
    string temperature();
  };
};
