module KitchenNaming
{
  interface Kitchen
  {
    string turnOnOff(in boolean onOff, in string appliance);
    string changeHeat();
    string openCloseDoor();
    string timer();
    string temperature();
  };
};
