module KitchenNaming
{
  interface Kitchen
  {
    string turnOnOff(in boolean onOff, in string appliance);
    string changeHeat(in double tempAmount, in string appliance);
    string openCloseDoor(in boolean openClose, in string appliance);
    string setTimer(in double time, in string appliance);
    string temperature();
  };
};
