package KitchenNaming;


/**
* KitchenNaming/Kitchen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Saturday, April 8, 2017 11:42:34 AM IST
*/

public interface Kitchen extends KitchenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Kitchen
