package KitchenNaming;


/**
* KitchenNaming/KitchenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Wednesday, March 29, 2017 9:19:35 PM IST
*/

public interface KitchenOperations 
{
  String turnOnOff (boolean onOff, String appliance);
  String changeHeat (double tempAmount, String appliance);
  String openCloseDoor (boolean openClose, String appliance);
  String setTimer (double time, String appliance);
  String temperature ();
} // interface KitchenOperations
