package KitchenNaming;


/**
* KitchenNaming/KitchenHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Thursday, March 16, 2017 9:26:44 PM GMT
*/

abstract public class KitchenHelper
{
  private static String  _id = "IDL:KitchenNaming/Kitchen:1.0";

  public static void insert (org.omg.CORBA.Any a, KitchenNaming.Kitchen that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KitchenNaming.Kitchen extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (KitchenNaming.KitchenHelper.id (), "Kitchen");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KitchenNaming.Kitchen read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_KitchenStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KitchenNaming.Kitchen value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static KitchenNaming.Kitchen narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof KitchenNaming.Kitchen)
      return (KitchenNaming.Kitchen)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      KitchenNaming._KitchenStub stub = new KitchenNaming._KitchenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static KitchenNaming.Kitchen unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof KitchenNaming.Kitchen)
      return (KitchenNaming.Kitchen)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      KitchenNaming._KitchenStub stub = new KitchenNaming._KitchenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
