package KitchenNaming;


/**
* KitchenNaming/KitchenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Sunday, April 2, 2017 8:47:41 PM IST
*/

public interface KitchenOperations 
{
  String turnOnOff (String json);
  String changeHeat (String json);
  String openCloseDoor (String json);
  String setTimer (String json);
  String temperature ();
} // interface KitchenOperations
