package KitchenNaming;


/**
* KitchenNaming/Kitchen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Sunday, April 2, 2017 9:04:08 PM IST
*/

public interface Kitchen extends KitchenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Kitchen
