package KitchenNaming;


/**
* KitchenNaming/KitchenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Saturday, March 11, 2017 2:48:13 PM GMT
*/

public interface KitchenOperations 
{
  String turnOnOff (boolean onOff, String appliance);
  String changeHeat ();
  String openCloseDoor (boolean openClose, String appliance);
  String timer ();
  String temperature ();
} // interface KitchenOperations
