package KitchenNaming;


/**
* KitchenNaming/Kitchen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Saturday, March 11, 2017 1:51:10 PM GMT
*/

public interface Kitchen extends KitchenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Kitchen
