package KitchenNaming;


/**
* KitchenNaming/Kitchen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kitchen.idl
* Thursday, March 16, 2017 9:26:44 PM GMT
*/

public interface Kitchen extends KitchenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Kitchen
